CP-310822: use stub_xc_domain_numa_get_node_pages from Xen
when it's available, and use a wrapper to decide when it's
not available.

This wrapper also prevents the link error below:

  File "ocaml/xenopsd/xc/dune", line 83, characters 7-21:
  83 |  (name xenops_xc_main)
              ^^^^^^^^^^^^^^
    /usr/bin/ld:
    /usr/lib64/ocaml/xenctrl/libxenctrl_stubs.a(xenctrl_stubs.o): in
    function `stub_xc_domain_numa_get_node_pages':
    (.text+0x1b70): multiple definition of
    `stub_xc_domain_numa_get_node_pages';
    ocaml/libs/xenctrl-ext/libxenctrl_ext_stubs.a(xenctrlext_stubs.o):/builddir/build/BUILD/xapi-25.39.0.35.gcdd7418ef/_b
    uild/default/ocaml/libs/xenctrl-ext/xenctrlext_stubs.c:700: first
    defined here
    collect2: error: ld returned 1 exit status

We are now always calling the implementation that is part of Xen. Our
own C code only manages conditional compilation and no longer provides a
redundant implementation.

Signed-off-by: Marcus Granado <marcus.granado@cloud.com>
Signed-off-by: Christian Lindig <christian.lindig@citrix.com>