Xapi_vdi.check_operation_error: factor out my_vbd_records
and use it in subsequent vals. This should also improve the performance,
because now we're doing one less Db.VBD.get_internal_records_where.

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>