CP-423204: add new xen field meminfo.claimed to xenctrlext
Only use meminfo[i].claimed if it is defined,
this avoids a link error in systems that don't have the claimed field:

xenctrlext_stubs.c:401:60: error: 'xc_meminfo_t' {aka 'struct
xen_sysctl_meminfo'} has no member named 'claimed'
  401 |             Store_field(info, 2,
      caml_copy_int64(meminfo[i].claimed));

and fix compilation error
File "ocaml/xenopsd/xc/numa.ml", line 58, characters 8-26:
58 |     let {memfree; memsize} = mem.(i) in

Signed-off-by: Marcus Granado <marcus.granado@cloud.com>