CP-53658: only use xc_domain_claim_pages_node if defined
this avoids a link error in systems that don't have this function:

/usr/bin/ld:
ocaml/libs/xenctrl-ext/libxenctrl_ext_stubs.a(xenctrlext_stubs.o): in
function `stub_xenctrlext_domain_claim_pages':
xen-api/_build/default/ocaml/libs/xenctrl-ext/xenctrlext_stubs.c:688:
undefined reference to `xc_domain_claim_pages_node'

set errno to ENOSYS if not defined, to keep behaviour
consistent with other stubs in this file.

keep CAMLparam4 in both cases to avoid unused parameter warnings.

Signed-off-by: Marcus Granado <marcus.granado@cloud.com>