Forkexecd: shut down the socket before closing in the child
The CI kept failing with:
```
Fatal error: exception Unix.Unix_error(Unix.ECONNRESET, "read", "")
Raised by primitive operation at Unix.read in file "unix.ml", line 258, characters 7-33
Called from Xapi_stdext_unix__Unixext.really_read in file "lib/xapi-stdext-unix/unixext.ml", line 425, characters 12-37
Called from Fecomms.read_raw_rpc in file "ocaml/forkexecd/lib/fecomms.ml", line 28, characters 2-38
```

ECONNRESET is quite unusual for a 'read', the Linux manpage doesn't mention
that as a possibility but the POSIX manpage does.
Forkexecd (the server) writes a response and immediately closes the socket, but
the manpage of 'close' says that 'shutdown' should be used before closing a
socket.

Use 'shutdown' before 'close' to avoid clients getting an ECONNRESET when
reading the last reply on the socket.

Only use 'shutdown' in the child because the same socket is used both in the
child and in the parent, and expected to be kept open in the child after the
parent has closed it.

Signed-off-by: Edwin Török <edwin.torok@cloud.com>