CA-395784: fix(xapi-fd-test): do not generate <1us timeouts
The float argument gets converted to microseconds when making the system call.
If it is <1us then it gets converted to 0, which has special meaning
* for select/epoll it means timeout immediately
* for setsockopt SO_RCVTIMEO it means never timeout

So do not generate tests with such small timeout, instead replace them with no delays.

We cannot call `QCheck2.assume` here (it can only be called from the body of a test),
 otherwise sometimes we might get a failure like this:
```
Test Dune__exe__Unixext_test.test_proxy failed:

ERROR: uncaught exception in generator for test Dune__exe__Unixext_test.test_proxy after 100 steps:
Exception: QCheck2.Failed_precondition
Backtrace: Raised at QCheck2.assume in file "src/core/QCheck2.ml" (inlined), line 57, characters 29-54
Called from Xapi_fd_test__Generate.delay_of_size in file "ocaml/libs/xapi-stdext/lib/xapi-fd-test/generate.ml", line 66, characters 2-34
Called from QCheck2.Tree.bind in file "src/core/QCheck2.ml", line 207, characters 28-31
Called from QCheck2.Gen.bind in file "src/core/QCheck2.ml", line 271, characters 72-80
Called from QCheck2.Tree.bind in file "src/core/QCheck2.ml", line 207, characters 28-31
Called from QCheck2.Test.check_state in file "src/core/QCheck2.ml", line 1749, characters 12-32
```

Signed-off-by: Edwin Török <edwin.torok@cloud.com>