Revert "CP-32659: define Volume.copy api"
SyntaxError: duplicate argument 'sr' in function definition (volume.py, line 1539)

This reverts commit adf13c0693eb645503ffa8aeca2f1e70004ed4f4.