CP-49136: Introduce PRNG for generating non-secret UUIDs
Not yet enabled by default, behind xapi.conf feature flag.
Will be enabled by default after more testing/auditing of the code.

Pool secret and Session are the only secret uuids/refs,
for everything else avoid the overhead of reading from /dev/urandom every time,
and use an internal PRNG.

Both the opaqueref and UUID of a Session is a secret, because you can retrieve one if you can guess the other,
so both must be created using CSPRNG.

This is about 15x faster than using /dev/urandom:
```
╭───────────────────────────────────────┬───────────────────────────┬───────────────────────────┬───────────────────────────╮
│name                                   │  major-allocated          │  minor-allocated          │  monotonic-clock          │
├───────────────────────────────────────┼───────────────────────────┼───────────────────────────┼───────────────────────────┤
│  uuidx creation/Uuidx.make            │             0.0001 mjw/run│             8.0001 mnw/run│             88.1485 ns/run│
│  uuidx creation/Uuidx.make_uuid_urnd  │             0.0000 mjw/run│            10.0014 mnw/run│           1369.9626 ns/run│
╰───────────────────────────────────────┴───────────────────────────┴───────────────────────────┴───────────────────────────╯
```

Uses the type system to ensure that we cannot create Refs or Uuids of type 'session' with the wrong function.
Example type error from a testcase that has ben fixed:
```
File "ocaml/tests/test_client.ml", line 18, characters 47-57:
18 |       Test_common.make_session ~__context ~ref:session_id
                                                    ^^^^^^^^^^
Error: This expression has type [< Uuidx.not_session ] Ref.t
       but an expression was expected of type [ `session ] Ref.t
       Type [< Uuidx.not_session ] = [< `session of [ `use_make_uuid_urnd ] ]
       is not compatible with type [ `session ]
       Types for tag `session are incompatible
```

Signed-off-by: Edwin Török <edwin.torok@cloud.com>